website/views.py
from flask import Blueprint, render_template, request, flash, jsonify
from flask_login import login_required, current_user
from .models import Note, Link, Photo
from . import db
import json

views = Blueprint('views', __name__)


@views.route('/home', methods=['GET', 'POST'])
@login_required
def home():
    photo_list = Photo.query.filter_by(user_id=current_user.id).order_by(Photo.date_posted.desc())
    if request.method == 'POST':
        note = request.form.get('note')

        if len(note) < 1:
            flash('Note is too short!', category='error')
        else:
            new_note = Note(data=note, user_id=current_user.id)
            db.session.add(new_note)
            db.session.commit()
            flash('Note Added!', category='success')
    return render_template("home.html", user=current_user, photos=photo_list)


@views.route('/delete-note', methods=['POST'])
def delete_note():
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()

    return jsonify({})


@views.route('/')
@views.route('/gallery')
# @login_required
def gallery():
    page = request.args.get('page', 1, type=int)
    photo_list = Photo.query.order_by(Photo.date_posted.desc()).paginate(page=page, per_page=12)
    return render_template("gallery.html", user=current_user, photos=photo_list)


@views.route('/links')
@login_required
def links():
    link_list = Link.query.all()
    return render_template("links.html", user=current_user, links=link_list)

website/templates/add_link.html
{% extends "base.html" %} {% block title %}Add Photo{% endblock %}

{% block content %}
    <div class="container">
        <h1>Add Link</h1>
        <p>Hello {{ current_user.userName }}, Please fill in the form to add a resource link.</p>

        <form method="POST" action="">
            <div class="form-group">
                <label for="name">Link Description</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Enter link description">
            </div>
            <div class="form-group">
                <label for="link">Link URL</label>
                <input type="text" class="form-control" id="link" name="link" placeholder="Enter link URL">
            </div>
            <br>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>

    </div>
{% endblock %}

website/templates/add_photo.html
{% extends "base.html" %} {% block title %}Add Photo{% endblock %}

{% block content %}
    <div class="container">
        <h1>Add Photo</h1>
        <p>Hello {{ current_user.userName }}, do you have the right to share this photo?</p>

        <form method="POST" action="" enctype="multipart/form-data">
            <fieldset class="form-group">

                <div class="form-group">
                    <label for="photo_name">Title of Photo</label>
                    <input type="text" class="form-control" id="photo_name" name="photo_name" placeholder="Enter photo title">
                </div>
                <div class="form-group">
                    <label for="photo_desc">Description of photo</label>
                    <input type="text" class="form-control" id="photo_desc" name="photo_desc" placeholder="Enter photo description">
                </div>
                <div class="form-group">
                    <label for="uploaded-file">Upload photo</label>
                    <input type="file" class="form-control" id="uploaded-file" name="uploaded-file" accept=".jpg">
<!--                    <input type="submit" value="UpLoad File">-->
                </div>
                <br>
                <button type="submit" class="btn btn-primary">Submit</button>

            </fieldset>
        </form>




    </div>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- links to get bootstrap x2 -->
    <link rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"/>
    <link rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"/>

<!-- link to get datatable manipulation code x2 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap5.css">
    <!-- local css -->
<!--    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">-->
    <link rel="stylesheet" type="text/css" href="static/css/style.css">
    <link rel="stylesheet" type="text/css" href="static/css/lightbox.min.css">

    <title>Macks Aperture {% block title %}Home{% endblock %}</title>
	<link rel="icon" type="image/x-icon" href="/static/img/favicon.ico">

</head>
<body>
<!-- banner graphic -->
    <div class="row">
        <div class="col-2"></div>
        <div class="col-4">
            <div class="logo">
                <img src="./static/img/macks-aperture-logo.png" class="img-fluid" />
            </div>
        </div>
        <div class="col-4">
            <div class="site-summary">
                <h4>Photography Club</h4>
                <p>A place where you can share your work or just learn more about the art</p>
                <p>Visit the Telegram channel at <a href="https://t.me/macksaperture" target="_blank" >https://t.me/macksaperture</a></p>
            </div>
        </div>
        <div class="col-2"></div>
    </div>

<!-- navigation bar at top of page defined by nav tag -->
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-dark bg-steel">
            <a class="navbar-brand mr-4" href="/">Macks Aperture Photography Club</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                <div class="navbar-nav ms-auto">
                  {% if user.is_authenticated %}
                  <a class="nav-item nav-link" id="home" href="/home">Home</a>
                  <a class="nav-item nav-link" id="gallery" href="/gallery">Gallery</a>
                  <a class="nav-item nav-link" id="links" href="/links">Resources</a>
                  <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                  {% else %}
                  <a class="nav-item nav-link" id="login" href="/login">Login</a>
                  <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
                  {% endif %}
                </div>
            </div>
        </nav>
    </div>

<!-- this is where the python-ish code goes, for loops and if statements -->
    <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
            {% if category == 'error' %}
            <div class="alert alert-danger alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% else %}
            <div class="alert alert-success alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endif %}
            {% endfor %}
        {% endif %}
        {% endwith %}
    </div>


<!-- div to hold the blocks from other page -->
    <div>{% block content %} {% endblock %}</div>

<!-- scripts for bootstrap framework x3 -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous">
    </script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous">
    </script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous">
    </script>

<!-- script for deleting notes  -->
    <script
      type="text/javascript"
      src="{{ url_for('static',  filename='index.js') }}">
    </script>

<!-- script for table search sort feature x3  -->
    <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap5.js"></script>
    {% block scripts %}{% endblock %}

</body>
</html>

website/templates/gallery.html
{% extends "base.html" %} {% block title %}Gallery{% endblock %}

{% block content %}
    <div class="container">
        <div class="gallery">
            {% if current_user.is_authenticated %}
                <p>Hello {{ current_user.userName }}</p>
            {% endif %}
            <h1 align="center">This is the Main Gallery page</h1>
            <h5 align="center">Image Gallery</h5>

            {% for photo in photos %}
                <a href="{{ photo.gallery_file }}" data-lightbox="mygallery" data-title="{{ photo.photo_name }}">
                <img src="{{ photo.thumb_file }}" alt="{{ photo.photo_name }}"></a>
<!--                <p>{{ photo.photo_name}}</p>-->
            {% endfor %}
        </div>

        <div class="border-top pt-3">
            {% for page_num in photos.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
              {% if page_num %}
                {% if photos.page == page_num %}
                  <a class="btn btn-info mb-4" href="{{ url_for('views.gallery', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                  <a class="btn btn-outline-info mb-4" href="{{ url_for('views.gallery', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
              {% else %}
               ...
              {% endif %}
            {% endfor %}

            {% if current_user.is_authenticated %}
                <small class="text-muted">
                    Want to add something? <a class="ml-2" href="/add_photo">Add your Photo</a>
                </small>
            {% endif %}
        </div>

    </div>

    <script src="./static/js/lightbox-plus-jquery.min.js"></script>

{% endblock %}

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %}

{% block content %}
    <!-- this code is just to read, write, and delete notes -->
    <div class="container">

        <p>Hello {{ current_user.userName }}</p>
        <h2 align="center">This is your personal home page</h2>

        <h2 align="center">Notes</h2>
        <ul class="list-group list-group-flush" id="notes">
        <!-- if current user has any notes, a for loop reads one note at a time
            out of the database and adds it to an HTML list item -->
            {% for note in user.notes %}
            <li class="list-group-item">{{ note.data }}
                <!-- each list item gets a button with code to delete a note by calling a script -->
                <!-- the script code in the base.html finishes this call -->
                <button type="button" class="close" onClick="deleteNote({{ note.id }})">
                    <span aria-hidden="true">&times;</span>
                </button>
            </li>
            {% endfor %}
        </ul>

    <!-- code to create a new note-->
        <form method="POST">
            <textarea name="note" id="note" class="form-control"></textarea>
            <br>
            <div align="center">
                <button type="submit" class="btn btn-primary">Add Note</button>
            </div>
        </form>

        <div class="gallery">
            <h2 align="center">here is your personal gallery</h2>
            {% for photo in photos %}
                <a href="{{ photo.gallery_file }}" data-lightbox="mygallery" data-title="{{ photo.photo_name }}">
                <img src="{{ photo.thumb_file }}" alt="{{ photo.photo_name }}"></a>
<!--                <p>{{ photo.photo_name}}</p>-->
            {% endfor %}
        </div>

        <div class="border-top pt-3">
            <small class="text-muted">
                Show off your stuff! <a class="ml-2" href="/add_photo">Add a Photo</a>
            </small>
        </div>

    </div>

    <script src="./static/js/lightbox-plus-jquery.min.js"></script>

{% endblock %}

website/templates/links.html
{% extends "base.html" %} {% block title %}Links{% endblock %}

{% block content %}
    <div class="container">
        <h2 align="center">Resource Links</h2>
        <table id="data"  class="table table-secondary table-bordered table-striped">
            <thead>
                <tr>
                    <th scope="col">Description</th>
                    <th scope="col">Link to resource</th>
                    <th scope="col">Date</th>
                    <th scope="col">By</th>
                </tr>
            </thead>
            <tbody class="table-group-divider table-sm">
            <!--build the table by adding records from the database one at a time with a for loop-->
            {% for link in links %}
                <tr>
                    <td>{{ link.name }}</td>
                    <td><a href="{{ link.link }}" target="_blank">{{ link.link }}</a></td>
                    <td>{{ link.create_date.strftime('%A %b %-d, %Y') }}</td>
                    <td>{{ user.userName }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

         <div class="border-top pt-3">
            <small class="text-muted">
                Do you know a good information resource? <a class="ml-2" href="/add_link">Add Link</a>
            </small>
        </div>

    </div>
{% endblock %}

<!-- script calls function to add search/sort/pagination -->
{% block scripts %}
  <script>
    $(document).ready(function () {
      $('#data').DataTable();
    });
  </script>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %}

{% block content %}
<div class="container">
<!--    build the login form-->
    <form method="POST">
        <h3 align="center">Login</h3>
        <div class="form-group">
            <label for="email">Email Address</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Enter password">
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
</div>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %}

{% block content %}
    <div class="container">
    <!--    build the sign up form-->
        <form method="POST">
            <h3 align="center">Sign Up</h3>
            <div class="form-group">
                <label for="email">Email Address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
            </div>
            <div class="form-group">
                <label for="userName">User Name</label>
                <input type="text" class="form-control" id="user_name" name="user_name" placeholder="Enter user name">
            </div>
            <div class="form-group">
                <label for="password1">Password</label>
                <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter password">
            </div>
            <div class="form-group">
                <label for="password2">Confirm password</label>
                <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm password">
            </div>
            <br>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}